export default {
    cloud_name: 'dlehndc9n',
    upload_preset: 'e9bahasc',
    api_key: '151992173381421',
    api_secret: 'f7xc11yowP29Gf8nNOjtiftxAh8',
    cdn_subdomain: false,
    cname: false,
    private_cdn: false,
    protocol: false,
    resource_type: false,
    responsive_class: false,
    responsive_use_breakpoints: false,
    responsive_width: false,
    round_dpr: true,
    secure: false,
    secure_cdn_subdomain: false,
    secure_distribution: false,
    shorten: false,
    type: false,
    url_suffix: false,
    use_root_path: false,
    version: false,
};
